### ISSUE TITLE
I got stuck with dovecot allocation

### ISSUE THREAD

**Issue by MichelDiz** [pedrogoncalvesk/rancher-catalog#1]
I just started the catalog and then I waited and got stuck in that problem. There is no other instance using the Dovecot ports. I am still analyzing the problem.

`dovecot (Failed to allocate instance [container:1i608]: Bad instance [container:1i608] in state [error]: Allocation failed: No healthy hosts meet the resource constraints: [127.0.0.1:19991:12345/tcp, 1430:143/tcp, 9930:993/tcp, 1100:110/tcp, 9950:995/tcp, 41900:4190/tcp portReservation, instanceReservation: 1].) `

**Comment by MichelDiz** [comment]
Have you thought about using Traefik for reverse proxy and balance?

**Comment by MichelDiz** [comment]
Changing the Public Host IP to 0.0.0.0:19991 works, but I got 404 page not found in the main domain.

:8084
```
400 Bad Request
The plain HTTP request was sent to HTTPS port
nginx
```

:8083
WORKS! xD


This can be closed, but I'll wait about the Traefik. I really think that Traefik worth while.

**Comment by MichelDiz** [comment]
One more issue the /SOGo isn't working or even /RC (RoundCube) - There is some working client in this Catalog?

EDIT:
```
http://mail.localtest.com:8083/SOGo/
Returns => 502 Bad Gateway
nginx
```

**Comment by pedropereirahg** [comment]
Have you tried to access http://mail.localtest.com/SOGo/ ?

For the reverse proxy I'm currently using [rancher-active-proxy](https://github.com/adi90x/rancher-active-proxy) on rancher instance, maybe that's will be helpful. 

I read about traefik, it looks amazing! Thank you a lot 😄 
But at the moment I think the best strategy is not to install the reverse proxy on the rancher stack, allowing each of you to use any other reverse proxy methods.

**Comment by MichelDiz** [comment]
Hi! I think what happened was something related to the updates. Like, I've added domains and e-mail boxes. Then you need to restart services. At that moment the service stops for good, and does not come back. Hence when he accessed the / SOGo / he returned unavailable.

When I returned the service from scratch and went straight to the / SOGo /. It worked. But when I add email accounts it stops working.

**Comment by etique57** [comment]
Thanks!

solved my issue indeed (I was looking on the rancherized github :))
